In [261]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [182]:
df = pd.read_csv("german_credit_data.csv")
df

Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0             0   67    male    2     own             NaN           little   
1             1   22  female    2     own          little         moderate   
2             2   49    male    1     own          little              NaN   
3             3   45    male    2    free          little           little   
4             4   53    male    2    free          little           little   
..          ...  ...     ...  ...     ...             ...              ...   
995         995   31  female    1     own          little              NaN   
996         996   40    male    3     own          little           little   
997         997   38    male    2     own          little              NaN   
998         998   23    male    2    free          little           little   
999         999   27    male    2     own        moderate         moderate   

     Credit amount  Duration              Purpose  Risk  
0             1169         6             radio/TV  good  
1             5951        48             radio/TV   bad  
2             2096        12            education  good  
3             7882        42  furniture/equipment  good  
4             4870        24                  car   bad  
..             ...       ...                  ...   ...  
995           1736        12  furniture/equipment  good  
996           3857        30                  car  good  
997            804        12             radio/TV  good  
998           1845        45             radio/TV   bad  
999           4576        45                  car  good  

[1000 rows x 11 columns]

# Feature engineering

Drop unesseccary column

In [183]:
df1 = df.drop(df.columns[0], axis=1)
df1

Age     Sex  Job Housing Saving accounts Checking account  Credit amount  \
0     67    male    2     own             NaN           little           1169   
1     22  female    2     own          little         moderate           5951   
2     49    male    1     own          little              NaN           2096   
3     45    male    2    free          little           little           7882   
4     53    male    2    free          little           little           4870   
..   ...     ...  ...     ...             ...              ...            ...   
995   31  female    1     own          little              NaN           1736   
996   40    male    3     own          little           little           3857   
997   38    male    2     own          little              NaN            804   
998   23    male    2    free          little           little           1845   
999   27    male    2     own        moderate         moderate           4576   

     Duration              Purpose  Risk  
0           6             radio/TV  good  
1          48             radio/TV   bad  
2          12            education  good  
3          42  furniture/equipment  good  
4          24                  car   bad  
..        ...                  ...   ...  
995        12  furniture/equipment  good  
996        30                  car  good  
997        12             radio/TV  good  
998        45             radio/TV   bad  
999        45                  car  good  

[1000 rows x 10 columns]

Age

In [184]:
df1["Age"].isnull().sum()

np.int64(0)

In [299]:
MAX_AGE = df1["Age"].max()

In [300]:
age = df1["Age"] / MAX_AGE
print(age)

0      0.893333
1      0.293333
2      0.653333
3      0.600000
4      0.706667
         ...   
995    0.413333
996    0.533333
997    0.506667
998    0.306667
999    0.360000
Name: Age, Length: 1000, dtype: float64


Sex

In [186]:
df1["Sex"].isnull().sum()

np.int64(0)

In [187]:
df1["Sex"].value_counts()

Sex
male      690
female    310
Name: count, dtype: int64

In [188]:
le_sex = LabelEncoder()
sex = le_sex.fit_transform(df1["Sex"])
sex = pd.DataFrame(sex, columns=["Sex"])
sex

Sex
0      1
1      0
2      1
3      1
4      1
..   ...
995    0
996    1
997    1
998    1
999    1

[1000 rows x 1 columns]

Job

In [189]:
df1["Job"].isnull().sum()

np.int64(0)

In [190]:
df1["Job"].value_counts()

Job
2    630
1    200
3    148
0     22
Name: count, dtype: int64

In [191]:
job = pd.get_dummies(df1["Job"], prefix="job count", dtype=int)
print(job)

     job count_0  job count_1  job count_2  job count_3
0              0            0            1            0
1              0            0            1            0
2              0            1            0            0
3              0            0            1            0
4              0            0            1            0
..           ...          ...          ...          ...
995            0            1            0            0
996            0            0            0            1
997            0            0            1            0
998            0            0            1            0
999            0            0            1            0

[1000 rows x 4 columns]


Housing columns

In [192]:
df1["Housing"].isnull().sum()

np.int64(0)

In [193]:
df1["Housing"].value_counts()

Housing
own     713
rent    179
free    108
Name: count, dtype: int64

In [194]:
house = pd.get_dummies(df1["Housing"], dtype=int)
print(house)

     free  own  rent
0       0    1     0
1       0    1     0
2       0    1     0
3       1    0     0
4       1    0     0
..    ...  ...   ...
995     0    1     0
996     0    1     0
997     0    1     0
998     1    0     0
999     0    1     0

[1000 rows x 3 columns]


*Saving accounts**

In [195]:
df1["Saving accounts"].isnull().sum()

np.int64(183)

In [196]:
df1["Saving accounts"].value_counts()

Saving accounts
little        603
moderate      103
quite rich     63
rich           48
Name: count, dtype: int64

In [197]:
saving_accounts = pd.get_dummies(df1["Saving accounts"], dtype=int)
print(saving_accounts)

     little  moderate  quite rich  rich
0         0         0           0     0
1         1         0           0     0
2         1         0           0     0
3         1         0           0     0
4         1         0           0     0
..      ...       ...         ...   ...
995       1         0           0     0
996       1         0           0     0
997       1         0           0     0
998       1         0           0     0
999       0         1           0     0

[1000 rows x 4 columns]


*Checking account**

In [198]:
df1["Checking account"].isnull().sum()

np.int64(394)

In [199]:
df1["Checking account"].value_counts()

Checking account
little      274
moderate    269
rich         63
Name: count, dtype: int64

In [200]:
checking_account = pd.get_dummies(df1["Checking account"], dtype=int)
print(checking_account)

     little  moderate  rich
0         1         0     0
1         0         1     0
2         0         0     0
3         1         0     0
4         1         0     0
..      ...       ...   ...
995       0         0     0
996       1         0     0
997       0         0     0
998       1         0     0
999       0         1     0

[1000 rows x 3 columns]


Credit amount

In [201]:
df1["Credit amount"].isnull().sum()

np.int64(0)

In [348]:
MAX_CREDIT_AMOUNT = df1["Credit amount"].max()

In [347]:
credit_amount = df1["Credit amount"] / MAX_CREDIT_AMOUNT
print(credit_amount)

0      0.063450
1      0.323003
2      0.113765
3      0.427812
4      0.264329
         ...   
995    0.094225
996    0.209347
997    0.043639
998    0.100141
999    0.248372
Name: Credit amount, Length: 1000, dtype: float64


Duration

In [203]:
df1["Duration"].isnull().sum()

np.int64(0)

In [353]:
MAX_DURATION = df1["Duration"].max()

In [354]:
duration = df1["Duration"] / MAX_DURATION
print(duration)

0      0.083333
1      0.666667
2      0.166667
3      0.583333
4      0.333333
         ...   
995    0.166667
996    0.416667
997    0.166667
998    0.625000
999    0.625000
Name: Duration, Length: 1000, dtype: float64


Purpose

In [205]:
df1["Purpose"].isnull().sum()

np.int64(0)

In [206]:
df1["Purpose"].value_counts()

Purpose
car                    337
radio/TV               280
furniture/equipment    181
business                97
education               59
repairs                 22
domestic appliances     12
vacation/others         12
Name: count, dtype: int64

In [207]:
purpose = pd.get_dummies(df1["Purpose"], dtype=int)
print(purpose)

     business  car  domestic appliances  education  furniture/equipment  \
0           0    0                    0          0                    0   
1           0    0                    0          0                    0   
2           0    0                    0          1                    0   
3           0    0                    0          0                    1   
4           0    1                    0          0                    0   
..        ...  ...                  ...        ...                  ...   
995         0    0                    0          0                    1   
996         0    1                    0          0                    0   
997         0    0                    0          0                    0   
998         0    0                    0          0                    0   
999         0    1                    0          0                    0   

     radio/TV  repairs  vacation/others  
0           1        0                0  
1           1  

Risk

In [208]:
df1["Risk"].isnull().sum()

np.int64(0)

In [209]:
df1["Risk"].value_counts()

Risk
good    700
bad     300
Name: count, dtype: int64

In [210]:
le_risk = LabelEncoder()
risk = le_risk.fit_transform(df1["Risk"])
risk

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,

# Input and output values

In [211]:
type(pd.DataFrame(age))

pandas.core.frame.DataFrame

In [212]:
type(house)

pandas.core.frame.DataFrame

In [213]:
house

free  own  rent
0       0    1     0
1       0    1     0
2       0    1     0
3       1    0     0
4       1    0     0
..    ...  ...   ...
995     0    1     0
996     0    1     0
997     0    1     0
998     1    0     0
999     0    1     0

[1000 rows x 3 columns]

In [214]:
X = pd.concat([age, sex, job, house, saving_accounts, checking_account, credit_amount, duration, purpose], axis="columns")
X

Age  Sex  job count_0  job count_1  job count_2  job count_3  free  \
0    0.893333    1            0            0            1            0     0   
1    0.293333    0            0            0            1            0     0   
2    0.653333    1            0            1            0            0     0   
3    0.600000    1            0            0            1            0     1   
4    0.706667    1            0            0            1            0     1   
..        ...  ...          ...          ...          ...          ...   ...   
995  0.413333    0            0            1            0            0     0   
996  0.533333    1            0            0            0            1     0   
997  0.506667    1            0            0            1            0     0   
998  0.306667    1            0            0            1            0     1   
999  0.360000    1            0            0            1            0     0   

     own  rent  little  ...  Credit amount  Duration  business  car  \
0      1     0       0  ...       0.063450  0.083333         0    0   
1      1     0       1  ...       0.323003  0.666667         0    0   
2      1     0       1  ...       0.113765  0.166667         0    0   
3      0     0       1  ...       0.427812  0.583333         0    0   
4      0     0       1  ...       0.264329  0.333333         0    1   
..   ...   ...     ...  ...            ...       ...       ...  ...   
995    1     0       1  ...       0.094225  0.166667         0    0   
996    1     0       1  ...       0.209347  0.416667         0    1   
997    1     0       1  ...       0.043639  0.166667         0    0   
998    0     0       1  ...       0.100141  0.625000         0    0   
999    1     0       0  ...       0.248372  0.625000         0    1   

     domestic appliances  education  furniture/equipment  radio/TV  repairs  \
0                      0          0                    0         1        0   
1                      0          0                    0         1        0   
2                      0          1                    0         0        0   
3                      0          0                    1         0        0   
4                      0          0                    0         0        0   
..                   ...        ...                  ...       ...      ...   
995                    0          0                    1         0        0   
996                    0          0                    0         0        0   
997                    0          0                    0         1        0   
998                    0          0                    0         1        0   
999                    0          0                    0         0        0   

     vacation/others  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
..               ...  
995                0  
996                0  
997                0  
998                0  
999                0  

[1000 rows x 26 columns]

In [215]:
Y = pd.DataFrame(risk, columns=["Risk"])
Y

Risk
0       1
1       0
2       1
3       1
4       0
..    ...
995     1
996     1
997     1
998     0
999     1

[1000 rows x 1 columns]

# Data split

In [216]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [217]:
X_train.shape

(800, 26)

In [218]:
y_train.shape

(800, 1)

In [219]:
X_test.shape

(200, 26)

In [220]:
y_test.shape

(200, 1)

# Build model

## Machine Learning

Naive_baye

In [221]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)
print(nb.score(X_test, y_test))

0.665


C:\Users\diass\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Logistic regression

In [222]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)
print(lr.score(X_test, y_test))

0.75


C:\Users\diass\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Decision tree

In [223]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
print(dt.score(X_test, y_test))

0.655


SVM

In [224]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train, y_train)
print(svm.score(X_test, y_test))

0.76


C:\Users\diass\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Random Forest

In [225]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)
print(rf.score(X_test, y_test))

C:\Users\diass\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


0.77


K Neighbors

In [226]:
from  sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
print(knn.score(X_test, y_test))

0.715


C:\Users\diass\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Gradient Boosting

In [227]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
gb.fit(X_train, y_train)
print(gb.score(X_test, y_test))

C:\Users\diass\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.755


## Deep Learning

In [228]:
import tensorflow as tf
from tensorflow import keras
from keras import layers, regularizers

Create a model


In [253]:
model = keras.Sequential()
model.add(keras.Input(shape=(26,)))
model.add(layers.Dense(100, activation="relu", name="Hidden1"))
model.add(layers.Dense(1, activation="softmax"))

print(model.summary())

Model: "sequential_34"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Hidden1 (Dense)                 │ (None, 100)            │         2,700 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_34 (Dense)                │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,801 (10.94 KB)

 Trainable params: 2,801 (10.94 KB)

 Non-trainable params: 0 (0.00 B)

None


Setup the model configuration

In [254]:
model.compile(
    loss=keras.losses.CategoricalCrossentropy(),
    optimizer=keras.optimizers.Adam(learning_rate=0.02),
    metrics=["accuracy"]
)

Make the model actualy train

In [255]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100


C:\Users\diass\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\ops\nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (32, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(
C:\Users\diass\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\losses\losses.py:27: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(32, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return self.fn(y_true, y_pred, **self._fn_kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6794 - loss: 0.0000e+00
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6881 - loss: 0.0000e+00 
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6848 - loss: 0.0000e+00
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6740 - loss: 0.0000e+00
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6857 - loss: 0.0000e+00
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6741 - loss: 0.0000e+00
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6795 - loss: 0.0000e+00  
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7099 - loss: 0.0000e+00
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6594 - loss: 0.0000e+00
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7010 - loss: 0.0000e+00
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6857 - loss: 0.0000e+00
Epoch 12/100
25/25 ━━━━━━━━━

Testing the model

In [256]:
model.evaluate(X_test, y_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7274 - loss: 0.0000e+00


C:\Users\diass\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\ops\nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (None, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(
C:\Users\diass\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\losses\losses.py:27: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return self.fn(y_true, y_pred, **self._fn_kwargs)


[0.0, 0.7400000095367432]

In [260]:
model.predict(X_train)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

Regularization (L2 or L1)

In [239]:
model_1 = keras.Sequential()
model_1.add(keras.Input(shape=(26,)))
model_1.add(layers.Dense(50, activation="relu", name="Hidden1", kernel_regularizer=regularizers.l2(0.05)))
model_1.add(layers.Dense(2, activation="softmax"))

model_1.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(),
    optimizer=keras.optimizers.Adam(learning_rate=0.02),
    metrics=["accuracy"]
)

model_1.fit(X_train, y_train, epochs=100)

model_1.evaluate(X_test, y_test)

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6376 - loss: 1.3481   
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6994 - loss: 0.6256
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7115 - loss: 0.6112
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7012 - loss: 0.5885
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6869 - loss: 0.5957
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6988 - loss: 0.5969
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7258 - loss: 0.5824
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7065 - loss: 0.5678   
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6962 - loss: 0.5870 
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7296 - loss: 0.5542
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7101 - loss: 0.5829
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - ac

[0.5046004056930542, 0.7549999952316284]

In [418]:
y_pred = model_1.predict(X_train)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


In [435]:

p = []
for pred in y_pred:
    p.append(pred.argmax(axis=0))


In [437]:
p = np.array(p)
p

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,

In [439]:
from sklearn.metrics import classification_report

print(classification_report(y_train, p))

              precision    recall  f1-score   support

           0       0.63      0.21      0.32       248
           1       0.73      0.95      0.82       552

    accuracy                           0.72       800
   macro avg       0.68      0.58      0.57       800
weighted avg       0.70      0.72      0.66       800



In [291]:
y_train

Risk
238     1
393     1
406     1
581     1
809     0
..    ...
60      1
400     1
702     1
268     0
306     1

[800 rows x 1 columns]

In [408]:
y_pred

array([[0.10309215, 0.89690787],
       [0.33512986, 0.66487014],
       [0.05258516, 0.9474148 ],
       ...,
       [0.23615198, 0.763848  ],
       [0.43213877, 0.56786126],
       [0.13517281, 0.86482716]], dtype=float32)

In [295]:
INDEX = 268

In [296]:
sample = np.array([X_train.iloc[INDEX]])
sample

array([[0.30666667, 1.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 1.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.85062961, 0.66666667, 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [297]:
y_train.iloc[INDEX]

Risk    0
Name: 887, dtype: int64

In [298]:
model_1.predict(sample)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[0.5698427 , 0.43015733]], dtype=float32)

In [394]:
age_samp = 18
sex_samp = "female"
job_samp = 0
house_samp = "free"
saving_accounts_samp = "little"
checking_account_samp = "little"
credit_amount_samp = 5234
duration_samp = 10
purpose_samp = "car"

In [401]:
def new_data_treatment(age_samp, sex_samp, job_samp, house_samp, saving_accounts_samp, checking_account_samp, credit_amount_samp, duration_samp, purpose_samp):
    age = np.array([age_samp / MAX_AGE])

    sex = np.array([1]) if sex_samp == "male" else np.array([0])

    job = np.zeros(4)
    job[job_samp]  = 1

    house = np.zeros(3)
    match house_samp:
        case "free":
            house[0] = 1
        case "own":
            house[1] = 1
        case "rent":
            house[2] = 1

    saving_accounts = np.zeros(4)
    match saving_accounts_samp:
        case "little":
            saving_accounts[0] = 1
        case "moderate":
            saving_accounts[1] = 1
        case "quite rich":
            saving_accounts[2] = 1
        case "rich":
            saving_accounts[3] = 1

    checking_account = np.zeros(3)
    match checking_account_samp:
        case "little":
            checking_account[0] = 1
        case "moderate":
            checking_account[1] = 1
        case "rich":
            checking_account[2] = 1

    credit_amount = np.array([credit_amount_samp / MAX_CREDIT_AMOUNT])

    duration = np.array([duration_samp / MAX_DURATION])

    purpose = np.zeros(8)
    match purpose_samp:
        case "business":
            purpose[0] = 1
        case "car":
            purpose[1] = 1
        case "domestic appliances":
            purpose[2] = 1
        case "education":
            purpose[3] = 1
        case "furniture/equipment":
            purpose[4] = 1
        case "radio/TV":
            purpose[5] = 1
        case "repairs":
            purpose[6] = 1
        case "vacation/others":
            purpose[7] = 1

    data = np.concat((age, sex, job, house, saving_accounts, checking_account, credit_amount, duration, purpose))
    return np.array([data])

In [403]:
data = new_data_treatment(18, "female", 0, "free", "little", "little", 5000, 10, "car")

In [404]:
model_1.predict(data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[0.6386853 , 0.36131474]], dtype=float32)

In [405]:
model_1.save("model_l1regularization.h5")

Early Stopping

In [234]:
model_2 = keras.Sequential()
model_2.add(keras.Input(shape=(26,)))
model_2.add(layers.Dense(100, activation="relu", name="Hidden1"))
model_2.add(layers.Dense(2, activation="softmax"))

model_2.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(),
    optimizer=keras.optimizers.Adam(learning_rate=0.02),
    metrics=["accuracy"]
)

from keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='val_loss', patience=10)

model_2.fit(X_train, y_train, epochs=100, callbacks=[early_stopping])

model_2.evaluate(X_test, y_test)

Epoch 1/100


25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6894 - loss: 0.6156
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7012 - loss: 0.5627  
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7804 - loss: 0.4897
Epoch 4/100


C:\Users\diass\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\callbacks\early_stopping.py:155: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: accuracy,loss
  current = self.get_monitor_value(logs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7878 - loss: 0.4677
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7486 - loss: 0.4912  
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7662 - loss: 0.4873
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7992 - loss: 0.4367 
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7668 - loss: 0.4515 
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8139 - loss: 0.4199
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7920 - loss: 0.4203
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7911 - loss: 0.4193
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8216 - loss: 0.3783
Epoch 13/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8399 - loss: 0.3581
Epoch 14/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8229 - loss: 0.3654
Epoch 15/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.81

[1.3596794605255127, 0.699999988079071]

Dropout

In [235]:
model_3 = keras.Sequential()
model_3.add(keras.Input(shape=(26,)))
model_3.add(layers.Dense(100, activation="relu", name="Hidden1"))
model_3.add(layers.Dropout(0.25))
model_3.add(layers.Dense(2, activation="softmax"))

model_3.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(),
    optimizer=keras.optimizers.Adam(learning_rate=0.02),
    metrics=["accuracy"]
)

model_3.fit(X_train, y_train, epochs=100)

model_3.evaluate(X_test, y_test)

Epoch 1/100


25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6596 - loss: 0.6324 
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6988 - loss: 0.5769
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7327 - loss: 0.5106  
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7358 - loss: 0.5150
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7469 - loss: 0.5298
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7866 - loss: 0.4607 
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7850 - loss: 0.4673
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7693 - loss: 0.4740
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7799 - loss: 0.4694
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7587 - loss: 0.4881
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8081 - loss: 0.4272
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7850 

[1.2310048341751099, 0.6800000071525574]